development:
  adapter: postgresql
  encoding: utf8
  database: spa_development
  pool: 5
  username: 
  password:

test: 
  adapter: postgresql
  encoding: utf8
  database: spa_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: spa_production
  pool: 5
  username: 
  password: